### ISSUE TITLE
Incomplete readme

### ISSUE THREAD

**Issue by LAfricain** [vss-devel/zimmer#1]
Hi,
I have issues with new version of zimwriterfs, and I would like to test zimmer for personal zim creation. Can somebody add some explanation in the readme file how to use it?
Thank you,

**Comment by vss-devel** [comment]
@LAfricain I've added some installation notes to the Readme. Hope this helps.

**Comment by LAfricain** [comment]
Thanks... Already better, but what means:
Symlink zimmer as zimwriterfs: ln -s zimmer.js <some directory in $PATH>/zimwriterfs
Make sure genuine zimwriterfs is not in the $PATH
I need zimwriterfs?
When I run npm install I have a lot af error:
`moi@ordi:~/Téléchargements/zimmer-master$ npm install`
`lzma-native@1.5.2 install /home/moi/Téléchargements/zimmer-master/node_modules/lzma-native
node-pre-gyp install --fallback-to-build`
/usr/bin/env: «node»: Aucun fichier ou dossier de ce type
zimmer@0.0.1 /home/moi/Téléchargements/zimmer-master
├─┬ async@2.1.5
│ └── lodash@4.17.4
├── bufferpack@0.0.6
├── csv-parse@1.2.0
├─┬ csv-stringify@1.0.4
│ └── lodash.get@4.4.2
├─┬ domutils@1.5.1
│ ├─┬ dom-serializer@0.1.0
│ │ └── domelementtype@1.1.3
│ └── domelementtype@1.3.0
├── expand-home-dir@0.0.3
├─┬ fs-extra@2.0.0
│ ├── graceful-fs@4.1.11
│ └── jsonfile@2.4.0
├─┬ htmlparser2@3.9.2
│ ├── domhandler@2.3.0
│ ├── entities@1.1.1
│ ├── inherits@2.0.3
│ └─┬ readable-stream@2.2.2
│   ├── buffer-shims@1.0.0
│   ├── core-util-is@1.0.2
│   ├── isarray@1.0.0
│   ├── process-nextick-args@1.0.7
│   ├── string_decoder@0.10.31
│   └── util-deprecate@1.0.2
├── long@3.2.0
├─┬ mime-types@2.1.14
│ └── mime-db@1.26.0
├─┬ mmmagic@0.4.5
│ └── nan@2.5.1
├─┬ path@0.12.7
│ ├── process@0.11.9
│ └─┬ util@0.10.3
│   └── inherits@2.0.1
├─┬ sqlite3@3.1.8
│ ├── nan@2.4.0
│ └─┬ node-pre-gyp@0.6.31
│   ├─┬ mkdirp@0.5.1
│   │ └── minimist@0.0.8
│   ├─┬ nopt@3.0.6
│   │ └── abbrev@1.0.9
│   ├─┬ npmlog@4.0.0
│   │ ├─┬ are-we-there-yet@1.1.2
│   │ │ ├── delegates@1.0.0
│   │ │ └─┬ readable-stream@2.1.5
│   │ │   ├── buffer-shims@1.0.0
│   │ │   ├── core-util-is@1.0.2
│   │ │   ├── inherits@2.0.3
│   │ │   ├── isarray@1.0.0
│   │ │   ├── process-nextick-args@1.0.7
│   │ │   ├── string_decoder@0.10.31
│   │ │   └── util-deprecate@1.0.2
│   │ ├── console-control-strings@1.1.0
│   │ ├─┬ gauge@2.6.0
│   │ │ ├── aproba@1.0.4
│   │ │ ├── has-color@0.1.7
│   │ │ ├── has-unicode@2.0.1
│   │ │ ├── object-assign@4.1.0
│   │ │ ├── signal-exit@3.0.1
│   │ │ ├─┬ string-width@1.0.2
│   │ │ │ ├─┬ code-point-at@1.0.1
│   │ │ │ │ └── number-is-nan@1.0.1
│   │ │ │ └─┬ is-fullwidth-code-point@1.0.0
│   │ │ │   └── number-is-nan@1.0.1
│   │ │ ├─┬ strip-ansi@3.0.1
│   │ │ │ └── ansi-regex@2.0.0
│   │ │ └── wide-align@1.1.0
│   │ └── set-blocking@2.0.0
│   ├─┬ rc@1.1.6
│   │ ├── deep-extend@0.4.1
│   │ ├── ini@1.3.4
│   │ ├── minimist@1.2.0
│   │ └── strip-json-comments@1.0.4
│   ├─┬ request@2.76.0
│   │ ├── aws-sign2@0.6.0
│   │ ├── aws4@1.5.0
│   │ ├── caseless@0.11.0
│   │ ├─┬ combined-stream@1.0.5
│   │ │ └── delayed-stream@1.0.0
│   │ ├── extend@3.0.0
│   │ ├── forever-agent@0.6.1
│   │ ├─┬ form-data@2.1.1
│   │ │ └── asynckit@0.4.0
│   │ ├─┬ har-validator@2.0.6
│   │ │ ├─┬ chalk@1.1.3
│   │ │ │ ├── ansi-styles@2.2.1
│   │ │ │ ├── escape-string-regexp@1.0.5
│   │ │ │ ├─┬ has-ansi@2.0.0
│   │ │ │ │ └── ansi-regex@2.0.0
│   │ │ │ ├─┬ strip-ansi@3.0.1
│   │ │ │ │ └── ansi-regex@2.0.0
│   │ │ │ └── supports-color@2.0.0
│   │ │ ├─┬ commander@2.9.0
│   │ │ │ └── graceful-readlink@1.0.1
│   │ │ ├─┬ is-my-json-valid@2.15.0
│   │ │ │ ├── generate-function@2.0.0
│   │ │ │ ├─┬ generate-object-property@1.2.0
│   │ │ │ │ └── is-property@1.0.2
│   │ │ │ ├── jsonpointer@4.0.0
│   │ │ │ └── xtend@4.0.1
│   │ │ └─┬ pinkie-promise@2.0.1
│   │ │   └── pinkie@2.0.4
│   │ ├─┬ hawk@3.1.3
│   │ │ ├── boom@2.10.1
│   │ │ ├── cryptiles@2.0.5
│   │ │ ├── hoek@2.16.3
│   │ │ └── sntp@1.0.9
│   │ ├─┬ http-signature@1.1.1
│   │ │ ├── assert-plus@0.2.0
│   │ │ ├─┬ jsprim@1.3.1
│   │ │ │ ├── extsprintf@1.0.2
│   │ │ │ ├── json-schema@0.2.3
│   │ │ │ └── verror@1.3.6
│   │ │ └─┬ sshpk@1.10.1
│   │ │   ├── asn1@0.2.3
│   │ │   ├── assert-plus@1.0.0
│   │ │   ├── bcrypt-pbkdf@1.0.0
│   │ │   ├── dashdash@1.14.0
│   │ │   ├── ecc-jsbn@0.1.1
│   │ │   ├── getpass@0.1.6
│   │ │   ├── jodid25519@1.0.2
│   │ │   ├── jsbn@0.1.0
│   │ │   └── tweetnacl@0.14.3
│   │ ├── is-typedarray@1.0.0
│   │ ├── isstream@0.1.2
│   │ ├── json-stringify-safe@5.0.1
│   │ ├─┬ mime-types@2.1.12
│   │ │ └── mime-db@1.24.0
│   │ ├── node-uuid@1.4.7
│   │ ├── oauth-sign@0.8.2
│   │ ├── qs@6.3.0
│   │ ├── stringstream@0.0.5
│   │ ├─┬ tough-cookie@2.3.2
│   │ │ └── punycode@1.4.1
│   │ └── tunnel-agent@0.4.3
│   ├─┬ rimraf@2.5.4
│   │ └─┬ glob@7.1.1
│   │   ├── fs.realpath@1.0.0
│   │   ├─┬ inflight@1.0.6
│   │   │ └── wrappy@1.0.2
│   │   ├── inherits@2.0.3
│   │   ├─┬ minimatch@3.0.3
│   │   │ └─┬ brace-expansion@1.1.6
│   │   │   ├── balanced-match@0.4.2
│   │   │   └── concat-map@0.0.1
│   │   ├─┬ once@1.4.0
│   │   │ └── wrappy@1.0.2
│   │   └── path-is-absolute@1.0.1
│   ├── semver@5.3.0
│   ├─┬ tar@2.2.1
│   │ ├── block-stream@0.0.9
│   │ ├─┬ fstream@1.0.10
│   │ │ └── graceful-fs@4.1.9
│   │ └── inherits@2.0.3
│   └─┬ tar-pack@3.3.0
│     ├─┬ debug@2.2.0
│     │ └── ms@0.7.1
│     ├─┬ fstream@1.0.10
│     │ ├── graceful-fs@4.1.9
│     │ └── inherits@2.0.3
│     ├─┬ fstream-ignore@1.0.5
│     │ ├── inherits@2.0.3
│     │ └─┬ minimatch@3.0.3
│     │   └─┬ brace-expansion@1.1.6
│     │     ├── balanced-match@0.4.2
│     │     └── concat-map@0.0.1
│     ├─┬ once@1.3.3
│     │ └── wrappy@1.0.2
│     ├─┬ readable-stream@2.1.5
│     │ ├── buffer-shims@1.0.0
│     │ ├── core-util-is@1.0.2
│     │ ├── inherits@2.0.3
│     │ ├── isarray@1.0.0
│     │ ├── process-nextick-args@1.0.7
│     │ ├── string_decoder@0.10.31
│     │ └── util-deprecate@1.0.2
│     └── uid-number@0.0.6
├── uuid@3.0.1
└─┬ yargs@6.6.0
  ├── camelcase@3.0.0
  ├─┬ cliui@3.2.0
  │ ├─┬ strip-ansi@3.0.1
  │ │ └── ansi-regex@2.1.1
  │ └── wrap-ansi@2.1.0
  ├── decamelize@1.2.0
  ├── get-caller-file@1.0.2
  ├─┬ os-locale@1.4.0
  │ └─┬ lcid@1.0.0
  │   └── invert-kv@1.0.0
  ├─┬ read-pkg-up@1.0.1
  │ ├─┬ find-up@1.1.2
  │ │ ├── path-exists@2.1.0
  │ │ └─┬ pinkie-promise@2.0.1
  │ │   └── pinkie@2.0.4
  │ └─┬ read-pkg@1.1.0
  │   ├─┬ load-json-file@1.1.0
  │   │ ├─┬ parse-json@2.2.0
  │   │ │ └─┬ error-ex@1.3.0
  │   │ │   └── is-arrayish@0.2.1
  │   │ ├── pify@2.3.0
  │   │ └─┬ strip-bom@2.0.0
  │   │   └── is-utf8@0.2.1
  │   ├─┬ normalize-package-data@2.3.5
  │   │ ├── hosted-git-info@2.2.0
  │   │ ├─┬ is-builtin-module@1.0.0
  │   │ │ └── builtin-modules@1.1.1
  │   │ ├── semver@5.3.0
  │   │ └─┬ validate-npm-package-license@3.0.1
  │   │   ├─┬ spdx-correct@1.0.2
  │   │   │ └── spdx-license-ids@1.2.2
  │   │   └── spdx-expression-parse@1.0.4
  │   └── path-type@1.1.0
  ├── require-directory@2.1.1
  ├── require-main-filename@1.0.1
  ├── set-blocking@2.0.0
  ├─┬ string-width@1.0.2
  │ ├── code-point-at@1.1.0
  │ └─┬ is-fullwidth-code-point@1.0.0
  │   └── number-is-nan@1.0.1
  ├── which-module@1.0.0
  ├── y18n@3.2.1
  └── yargs-parser@4.2.1

npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! lzma-native@1.5.2 install: `node-pre-gyp install --fallback-to-build`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the lzma-native@1.5.2 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the lzma-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs lzma-native
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls lzma-native
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/moi/Téléchargements/zimmer-master/npm-debug.log
And finally, what the command to create a zim?
Best regards, L'Africain

**Comment by vss-devel** [comment]
It looks like there is some problem with `node-pre-gyp install --fallback-to-build`.

[stackoverflow](http://stackoverflow.com/questions/33463945/node-pre-gyp-install-fallback-to-build-failed-during-meanjs-installation-on) suggests to try `npm install -g node-gyp`.

Otherwise there is something with *lzma-native* package. Try upgrading node and npm (I've got node v6.9.5 and npm 4.0.5). If not, then try to chase lzma-native developer.

Are you going to use zimmer with MWoffliner? if so you'd need to make an alias from zimmer to the name *zimwriterfs*, so MWoffliner will able to use it. Hence `ln -s` is a solution. This alias needs to be located somewhere in the $PATH.

Someone reported me back that it works fine this way.

Command line parameters for zimmer are the same as for zimwriterfs.

**Comment by LAfricain** [comment]
Ok thank you for the solution, I will test it.
> Are you going to use zimmer with MWoffliner?

No, I would like just to convert a folder (local site with special documentation) to zim. I did already with zimwriterfs but on Ubuntu 16.04 zimwriterfs won't run correctly.
What the advantage to use MWoffliner?

**Comment by vss-devel** [comment]
> No, I would like just to convert a folder

In this case there is no need to bother with symlinking. Just run zimmer.js with a folder path. "-h" option will give a list of extra options.

> What the advantage to use MWoffliner?

[MWoffliner](www.openzim.org/wiki/Build_your_ZIM_file#MWoffliner) is a tool for scraping [mediawiki](https://www.mediawiki.org)-based wikis (wikipedia, etc.). Apparently you don't need it in your case.

**Comment by LAfricain** [comment]
>     No, I would like just to convert a folder
>
> In this case there is no need to bother with symlinking. Just run 
> zimmer with a folder path. "-h" option will give a list of extra options.
>
Like that : nodejs zimmer.js /pathofmyfolder or like that ./zimmer.js 
/pathofmyfolder.
What about favicon, main page (index) or Welcome page?

./zimmer.js /home/portioncule/Documents/GraphoN/data/
/usr/bin/env: «node»: Aucun fichier ou dossier de ce type

**Comment by vss-devel** [comment]
> Like that : nodejs zimmer.js /pathofmyfolder or like that ./zimmer.js /pathofmyfolder.

./zimmer.js is better for large data as it sets some larger memory limits. Just make it executable.

> What about favicon, main page (index) or Welcome page?

Check ./zimmer.js -h for defaults otherwise specify your file names. [favicon](http://www.openzim.org/wiki/Metadata) is 48x48 png

**Comment by LAfricain** [comment]
Firsl when I run:

  ./zimmer.js -h

Terminal returns:

/usr/bin/env: «node»: Aucun fichier ou dossier de ce type

I did :

sudo ln -s /usr/bin/nodejs /usr/bin/node

It's ok for it, but now when I run:

./zimmer.js -h

module.js:328

     throw err;

     ^

Error: Cannot find module 'lzma-native'

     at Function.Module._resolveFilename (module.js:326:15)

     at Function.Module._load (module.js:277:25)

     at Module.require (module.js:354:17)

     at require (internal/module.js:12:17)

     at Object.<anonymous> (/home/moi/Téléchargements/zimmer-master/zimmer.js:40:12)

     at Module._compile (module.js:410:26)

     at Object.Module._extensions..js (module.js:417:10)

     at Module.load (module.js:344:32)

     at Function.Module._load (module.js:301:12)

     at Function.Module.runMain (module.js:442:10)

How can I resolve the lzma-native problem?
Thank you a lot for your help.
I have the package lzma lzma-dev installed

**Comment by vss-devel** [comment]
> Error: Cannot find module 'lzma-native'

Apparently 'lzma-native' is not installed. You need first to make `npm install` to run without errors, so all the dependencies are installed. See my earlier comment.

**Comment by LAfricain** [comment]
Le 21/02/2017 à 16:26, Vadim Shlyakhov a écrit :
>
>     Error: Cannot find module 'lzma-native'
>
> Apparently 'lzma-native' is not installed. You need first to make |npm 
> install| to run without errors, so all the dependencies are installed. 
> See my earlier comment.
>
I did the command : |npm install -g node-gyp|.
  without errors.
Now I need to do again npm install?

**Comment by vss-devel** [comment]
> Now I need to do again npm install?

Yes

**Comment by LAfricain** [comment]
Le 21/02/2017 à 16:30, Vadim Shlyakhov a écrit :
>
>     Now I need to do again npm install?
>
> Yes
>
Ok no errors.
Now when I run: ./zimmer.js -h
module.js:328
     throw err;
     ^

Error: Cannot find module 
'/home/moi/Téléchargements/zimmer-master/node_modules/sqlite3/lib/binding/node-v46-linux-x64/node_sqlite3.node'
     at Function.Module._resolveFilename (module.js:326:15)
     at Function.Module._load (module.js:277:25)
     at Module.require (module.js:354:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> 
(/home/moi/Téléchargements/zimmer-master/node_modules/sqlite3/lib/sqlite3.js:4:15)
     at Module._compile (module.js:410:26)
     at Object.Module._extensions..js (module.js:417:10)
     at Module.load (module.js:344:32)
     at Function.Module._load (module.js:301:12)
     at Module.require (module.js:354:17)

Error with sqlite3!!
I run: npm install sqlite3
And I did that https://github.com/TryGhost/Ghost/issues/5911 it solved 
the problem, now new issue...

./zimmer.js -h
module.js:328
     throw err;
     ^

Error: Cannot find module '../build/Release/magic'
     at Function.Module._resolveFilename (module.js:326:15)
     at Function.Module._load (module.js:277:25)
     at Module.require (module.js:354:17)
     at require (internal/module.js:12:17)

???

**Comment by vss-devel** [comment]
Did you run `npm install` (w/o specifying a package)? It must install all dependencies automatically (see `package.json`).

If so perhaps your npm is too old. Try to upgrade it or install all the deps. one by one manually. 

It looks like you need these: mime-db, mime-types, mmmagic.

**Comment by LAfricain** [comment]
Le 21/02/2017 à 17:07, Vadim Shlyakhov a écrit :
>
> Did you run |npm install| (w/o specifying a package)? It must install 
> all dependencies automatically (see |package.json|).
>
> If so perhaps your npm is too old. Try to upgrade it or install all 
> the deps. one by one manually.
>
Ok I'll try an upgrade, but how to do it manually?

**Comment by vss-devel** [comment]
> how to do it manually?

`npm install mime-db`
`npm install mime-types`
`npm install mmmagic`

**Comment by LAfricain** [comment]
Le 21/02/2017 à 17:37, Vadim Shlyakhov a écrit :
>
>     how to do it manually?
>
> |npm install mime-db|
> |npm install mime-types|
> |npm install mmmagic|
>
I run the 3 commands, still the same error :

./zimmer.js -h
module.js:328
     throw err;
     ^

Error: Cannot find module '../build/Release/magic'
     at Function.Module._resolveFilename (module.js:326:15)
     at Function.Module._load (module.js:277:25)
     at Module.require (module.js:354:17)
     at require (internal/module.js:12:17)
     at Object.<anonymous> (/home/cyrille/Téléchargements/zimmer-master/node_modules/mmmagic/lib/index.js:3:13)
     at Module._compile (module.js:410:26)
     at Object.Module._extensions..js (module.js:417:10)
     at Module.load (module.js:344:32)
     at Function.Module._load (module.js:301:12)
     at Module.require (module.js:354:17)

maybe I need absolutely to use a newer version...

**Comment by LAfricain** [comment]
Ok !
npm rebuild mmmagic
Solved the problem!!
Now ./zimmer -h give me:

Pack a directory into a zim file
Usage: /usr/bin/nodejs zimmer.js
Example: /usr/bin/nodejs zimmer.js

Options:
   -h, --help         Affiche de l'aide                                 
[booléen]
   -w, --welcome                                            [défaut: 
"index.htm"]
   -f, --favicon                                          [défaut: 
"favicon.png"]
   -l, --language [défaut: "eng"]
   -t, --title [défaut: ""]
   -d, --description [défaut: ""]
   -c, --creator [défaut: ""]
   -p, --publisher [défaut: ""]
   -r, --redirects [défaut: ""]

But new problem when I want to run the zim:
./zimmer.js /home/lui/Documents/GraphoN/data/
/home/moi/Téléchargements/zimmer-master/zimmer.js:1111
     out.write(Buffer.alloc(headerLength + maxMimeLength));
                      ^

TypeError: Buffer.alloc is not a function
     at initialise (/home/m/Téléchargements/zimmer-master/zimmer.js:1111:22)
     at 
/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:3686:9
     at replenish 
(/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:881:17)
     at 
/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:885:9
     at eachOfLimit 
(/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:912:22)
     at 
/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:917:16
     at _parallel 
(/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:3685:5)
     at Object.series 
(/home/m/Téléchargements/zimmer-master/node_modules/async/dist/async.js:4525:3)
     at core (/home/m/Téléchargements/zimmer-master/zimmer.js:1248:11)
     at main (/home/moi/Téléchargements/zimmer-master/zimmer.js:1334:5)

**Comment by vss-devel** [comment]
> TypeError: Buffer.alloc is not a function

Ah, your `node` is too old as [Buffer.alloc](https://nodejs.org/api/buffer.html#buffer_class_method_buffer_alloc_size_fill_encoding) is not available in node v4.2.6.  The later one uses `new Buffer(size)` but it's deprecated since v6.0.0.

In principle you'd try replacing Buffer.alloc() with new Buffer(), but I'm not sure it's worth an effort. In a long run upgrading node and npm looks like a better option.

BTW zimmer was tested with node v6. These were some issues with lzma-native at node v7.

**Comment by LAfricain** [comment]
Ok, I'll download the version, the LTS 6 is ok or it's better the 7?

**Comment by vss-devel** [comment]
> Ok, I'll download the version, the LTS 6 is ok or it's better the 7?

Version 6 is just fine.

**Comment by LAfricain** [comment]
Hi,
I did the update to 6 version:
installing it, and running `npm install` now it's ok.
But new error:
./zimmer.js /home/kizito/Documents/GraphoN/data/
/home/kizito/zimmer-master/zimmer.js:466
    return !! mimeDb[mimeType].compressible;
                              ^

TypeError: Cannot read property 'compressible' of undefined
    at FileArticle.Article.isCompressible (/home/kizito/zimmer-master/zimmer.js:466:31)
    at Object.ClusterBuilder.append (/home/kizito/zimmer-master/zimmer.js:387:32)
    at FileArticle.Article.storeData (/home/kizito/zimmer-master/zimmer.js:476:20)
    at nextTask (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5070:14)
    at Object.waterfall (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5073:5)
    at FileArticle.<anonymous> (/home/kizito/zimmer-master/zimmer.js:491:15)
    at /home/kizito/zimmer-master/node_modules/async/dist/async.js:359:16
    at nextTask (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5057:29)
    at /home/kizito/zimmer-master/node_modules/async/dist/async.js:5064:13
    at apply (/home/kizito/zimmer-master/node_modules/async/dist/async.js:21:25)

Some proposition?
It begun to create a zim file of 54,6M, and it stop.

**Comment by vss-devel** [comment]
Can you uncomment line 457:
` //~ log('isCompressible', this);`
to become 
` log('isCompressible', this);`

Then add `-v` to your command line and see that's in the output just before the error trace.

**Comment by LAfricain** [comment]
I uncomment line, now in the terminal:
./zimmer.js -l "fr" -t "GraphoN" /home/kizito/Documents/GraphoN/data/ GraphoN.zim -v
{ _: [ '/home/kizito/Documents/GraphoN/data/', 'GraphoN.zim' ],
  v: true,
  verbose: true,
  x: false,
  inflateHtml: false,
  u: false,
  uniqueNamespace: false,
  help: false,
  h: false,
  l: 'fr',
  language: 'fr',
  t: 'GraphoN',
  title: 'GraphoN',
  w: 'index.htm',
  welcome: 'index.htm',
  f: 'favicon.png',
  favicon: 'favicon.png',
  d: '',
  description: '',
  c: '',
  creator: '',
  p: '',
  publisher: '',
  r: '',
  redirects: '',
  '$0': '/usr/bin/nodejs zimmer.js',
  m: undefined }
reserving space for header and mime type list
RedirectArticle - favicon Ifavicon.png RedirectArticle {
  mimeType: '@REDIRECT@',
  nameSpace: '-',
  url: 'favicon',
  title: '',
  data: null,
  ordinal: null,
  dirEntry: null,
  redirect: 'Ifavicon.png' }
RedirectArticle - mainPage Aindex.htm RedirectArticle {
  mimeType: '@REDIRECT@',
  nameSpace: '-',
  url: 'mainPage',
  title: '',
  data: null,
  ordinal: null,
  dirEntry: null,
  redirect: 'Aindex.htm' }
Article.prototype.process Title
Article.prototype.process Creator
Article.prototype.process Publisher
Article.prototype.process Date
Article.prototype.process Description
Article.prototype.process Language
loadFiles start
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Title',
  title: '',
  data: <Buffer 47 72 61 70 68 6f 4e>,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append true 0 0 7 Title
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Creator',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append false 1 0 0 Creator
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Publisher',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append false 1 1 0 Publisher
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Date',
  title: '',
  data: <Buffer 32 30 31 37 2d 30 32 2d 32 34>,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append true 0 1 10 Date
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Description',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append false 1 2 0 Description
isCompressible Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Language',
  title: '',
  data: <Buffer 66 72>,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append true 0 2 2 Language
scanDirectory 
storeDirEntry 0 0 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Title',
  title: '',
  data: <Buffer 47 72 61 70 68 6f 4e>,
  ordinal: null,
  dirEntry: null }
storeDirEntry 1 0 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Creator',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
storeDirEntry 1 1 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Publisher',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
storeDirEntry 0 1 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Date',
  title: '',
  data: <Buffer 32 30 31 37 2d 30 32 2d 32 34>,
  ordinal: null,
  dirEntry: null }
storeDirEntry 1 2 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Description',
  title: '',
  data: <Buffer >,
  ordinal: null,
  dirEntry: null }
storeDirEntry 0 2 0 Article {
  mimeType: 'text/plain',
  nameSpace: 'M',
  url: 'Language',
  title: '',
  data: <Buffer 66 72>,
  ordinal: null,
  dirEntry: null }
storeArticleEntry done null 592 16 Title
storeArticleEntry done null 615 16 Creator
storeArticleEntry done null 640 16 Publisher
storeArticleEntry done null 667 16 Date
storeArticleEntry done null 689 16 Description
storeArticleEntry done null 718 16 Language
Article.prototype.process Convert_iso-8859-1_orig.sh
Article.prototype.process GraphoN_index.htm
isCompressible FileArticle {
  mimeType: 'application/x-sh',
  nameSpace: '-',
  url: 'Convert_iso-8859-1_orig.sh',
  title: '',
  data: <Buffer 23 21 2f 62 69 6e 2f 62 61 73 68 0a 0a 66 69 6e 64 20 2d 74 79 70 65 20 66 20 5c 28 20 2d 6e 61 6d 65 20 22 2a 2e 68 74 6d 6c 22 20 2d 6f 20 2d 6e 61 ... >,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append true 0 3 411 Convert_iso-8859-1_orig.sh
Article.prototype.process Graphon.png
storeDirEntry 0 3 1 FileArticle {
  mimeType: 'application/x-sh',
  nameSpace: '-',
  url: 'Convert_iso-8859-1_orig.sh',
  title: '',
  data: <Buffer 23 21 2f 62 69 6e 2f 62 61 73 68 0a 0a 66 69 6e 64 20 2d 74 79 70 65 20 66 20 5c 28 20 2d 6e 61 6d 65 20 22 2a 2e 68 74 6d 6c 22 20 2d 6f 20 2d 6e 61 ... >,
  ordinal: null,
  dirEntry: null }
storeArticleEntry done null 744 16 Convert_iso-8859-1_orig.sh
alterLinks 12
isCompressible FileArticle {
  mimeType: 'text/html',
  nameSpace: 'A',
  url: 'GraphoN_index.htm',
  title: 'BiblioN : Index général',
  data: <Buffer 3c 21 44 4f 43 54 59 50 45 20 68 74 6d 6c 20 50 55 42 4c 49 43 20 22 2d 2f 2f 57 33 43 2f 2f 44 54 44 20 48 54 4d 4c 20 34 2e 30 31 20 54 72 61 6e 73 ... >,
  ordinal: null,
  dirEntry: null }
...
  ordinal: null,
  dirEntry: null }
storeDirEntry 6 53 2 FileArtic
  title: '2000_livres_religieux_gratuits_telechargeables_sur_jesusmarie.com',
  data: <Buffer 3c 21 64 6f 63 74 79 70 65 20 68 74 6d 6c 20 70 75 62 6c 69 63 20 22 2d 2f 2f 77 33 63 2f 2f 64 74 64 20 68 74 6d 6c 20 34 2e 30 20 74 72 61 6e 73 69 ... >,
  ordinal: null,
  dirEntry: null }
storeArticleEntry done null 53681806 16 Apophtegmes/apophtegmes_3.html
storeArticleEntry done null 53681919 16 Apophtegmes/apophtegmes_1.html
scanDirectory Barbet
Article.prototype.process Barbet/PASSION.htm
Article.prototype.process Barbet/Thumbs.db
Article.prototype.process Barbet/_index.htm
alterLinks 1
isCompressible FileArticle {
  mimeType: 'text/html',
  nameSpace: 'A',
  url: 'Barbet/PASSION.htm',
  title: 'LA PASSION CORPORELLE DE JESUS (1) ',
  data: <Buffer 3c 68 74 6d 6c 20 78 6d 6c 6e 73 3a 6f 3d 22 75 72 6e 3a 73 63 68 65 6d 61 73 2d 6d 69 63 72 6f 73 6f 66 74 2d 63 6f 6d 3a 6f 66 66 69 63 65 3a 6f 66 ... >,
  ordinal: null,
  dirEntry: null }
ClusterBuilder.append true 6 54 48232 Barbet/PASSION.htm
storeDirEntry 6 54 2 FileArticle {
  mimeType: 'text/html',
  nameSpace: 'A',
  url: 'Barbet/PASSION.htm',
  title: 'LA PASSION CORPORELLE DE JESUS (1) ',
  data: <Buffer 3c 68 74 6d 6c 20 78 6d 6c 6e 73 3a 6f 3d 22 75 72 6e 3a 73 63 68 65 6d 61 73 2d 6d 69 63 72 6f 73 6f 66 74 2d 63 6f 6d 3a 6f 66 66 69 63 65 3a 6f 66 ... >,
  ordinal: null,
  dirEntry: null }
storeArticleEntry done null 53682032 16 Barbet/PASSION.htm
FileArticle.prototype.load mimeMagic.detect null application/CDFV2 Barbet/Thumbs.db
isCompressible FileArticle {
  mimeType: 'application/CDFV2',
  nameSpace: '-',
  url: 'Barbet/Thumbs.db',
  title: '',
  data: <Buffer d0 cf 11 e0 a1 b1 1a e1 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 3e 00 03 00 fe ff 09 00 06 00 00 00 00 00 00 00 00 00 00 00 01 00 00 00 01 00 ... >,
  ordinal: null,
  dirEntry: null }
/home/kizito/zimmer-master/zimmer.js:466
    return !! mimeDb[mimeType].compressible;
                              ^

TypeError: Cannot read property 'compressible' of undefined
    at FileArticle.Article.isCompressible (/home/kizito/zimmer-master/zimmer.js:466:31)
    at Object.ClusterBuilder.append (/home/kizito/zimmer-master/zimmer.js:387:32)
    at FileArticle.Article.storeData (/home/kizito/zimmer-master/zimmer.js:476:20)
    at nextTask (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5070:14)
    at Object.waterfall (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5073:5)
    at FileArticle.<anonymous> (/home/kizito/zimmer-master/zimmer.js:491:15)
    at /home/kizito/zimmer-master/node_modules/async/dist/async.js:359:16
    at nextTask (/home/kizito/zimmer-master/node_modules/async/dist/async.js:5057:29)
    at /home/kizito/zimmer-master/node_modules/async/dist/async.js:5064:13
    at apply (/home/kizito/zimmer-master/node_modules/async/dist/async.js:21:25)
kizito@U30Sd:~/zimmer-master$ 

OK I suppress the thumb.db file it  runs longer....
And it failed with the oledata.mso file I suppress it I'll see. Very good the verbose option!

**Comment by LAfricain** [comment]
Ok it's done! Now new problem, the internal links and not accessible. Exemple, in my directory I have differents directories for each authors, but when I click on the link I have a blank page.

**Comment by LAfricain** [comment]
New readme file it it can help, for me the "bug" is solved, installation ok, usage ok. Now stay the problem of folders.

[README.md.zip](https://github.com/vadp/zimmer/files/801831/README.md.zip)

**Comment by vss-devel** [comment]
> TypeError: Cannot read property 'compressible' of undefined

This must be fixed by commit the 391887f

Thanks for README!
