### ISSUE TITLE
Does wikizimmer resume?

### ISSUE THREAD

**Issue by pangoSE** [vss-devel/zimmer#14]
I'm trying to copy a very large wiki with millions of articles. 
It does not seem to resume and quickly skip what has already been downloaded.
Is this correct?

**Comment by vss-devel** [comment]
No, unfortunately it doesn't have a resume feature, sorry. 

wikizimmer is a simple tool and I never needed resume so far. Perhaps in some rather distant future it will have it, but not for the moment.
