### ISSUE TITLE
Node 12 Compatibility (w/ fix)

### ISSUE THREAD

**Issue by JGKle** [vss-devel/zimmer#16]
npm i fails to build, because the referenced version of "sharp" doesn't yet support Node 12.  See: https://github.com/lovell/sharp/issues/1668

Fix: Increase the version of node in package.json from 0.17.3 to 0.22.1.

**Comment by vss-devel** [comment]
Thanks. It's fixed in 7693849cb1d180b98a991a0b1f6ab2fb4ccf8779.
