### ISSUE TITLE
NPM Fails (request & uuid/v4 missing)

### ISSUE THREAD

**Issue by adfafafewaf** [vss-devel/zimmer#17]
* After checking out & doing "npm i" (& making the fix mentioned in issue #16), running the "wikizimmer" command crashes, saying it cannot find module "request."  Manually installing "npm i request" fixes it.

* Subsequently running the "zimmer" command crashes, saying it cannot find module uuid/v4. Unfortunately, I can't get this to install - "npm i uuid/v4" shows a Github login (which I found a bit odd), but even if I do login, it gets stuck.  So it seems there's no way to build the zim.

**Comment by metal450** [comment]
Oops!  Sorry, that was me - I didn't want to put my real github credentials into that suspicious-seeming popup when I tried to npm i uuid/v4 :)

**Comment by metal450** [comment]
Update: this can be fixed by changing zimmer.js, line 45 from:

    const uuidv4 = require( "uuid/v4" )

To:

    const { v4: uuidv4 } = require('uuid')

**Comment by vss-devel** [comment]
Thanks. This should be fixed in f944e57943d08b69e047dd1b26ec96ffbf7bbceb.
