### ISSUE TITLE
Files created by zimmer don't work in Kiwix Desktop / Serve

### ISSUE THREAD

**Issue by JGKle** [vss-devel/zimmer#18]
Finally I come to the main issue I was trying to report (the other issues arose when trying to rebuild a zim, just to make sure this issue was still present): It seems that files created by zimmer cannot be opened by any of the current "Official" Kiwix software.  To reproduce:

* node wikizimmer http://prepaid-data-sim-card.wikia.com/wiki/Alaska
* node zimmer --optimg prepaid-data-sim-card.wikia.com
* Download Kiwix Desktop for Windows from https://www.kiwix.org/en/downloads/, & try to open the .zim file.  It crashes.
* Download Kiwix Tools from https://www.kiwix.org/en/downloads/kiwix-serve, & try: kiwix-manage.exe test.xml add thezim.zim. It reports "Assertion failed" & exits.
* Likewise, kiwix-serve.exe thezim.zim reports the same assertion & exits.

Note that I also reported this to the kiwix people awhile back, but it doesn't seem like they'll fix it, as it only happens for zims from zimmer. However, you can see the many errors reported by zimcheck in that report here: https://github.com/kiwix/kiwix-desktop/issues/270

**Comment by vss-devel** [comment]
Just checked. It's fine with the Linux version of the Kiwix. 

BTW this download needs some clean up:

`wikizimmer.js https://prepaid-d~ki/Alaska --remove nav,iframe,.editsection`

**Comment by JGKle** [comment]
Correct, zims produced with zimmer work on Linux, but not on Windows.

**Comment by vss-devel** [comment]
Kiwix at the Windows 7 crashes for me  even before it opens any window.

Kiwix for Android is fine with the zim generated.

**Comment by JGKle** [comment]
>>Kiwix at the Windows 7 crashes for me even before it opens any window.

Yup, exactly.  You can see the underlying error by trying to open it with any of the kiwix-tools from commandline, i.e.

    kiwix-serve.exe prepaid-data-sim-card.wikia.com.zim

The error it shows (same as kiwix-manage, & presumably the same underlying error that crashes the desktop app) is:

    Assertion failed at ../../SOURCE/libzim_release/src/file_reader.cpp:88
     offset.v[1012801] < _size.v[1012801]

**Comment by vss-devel** [comment]
> > > Kiwix at the Windows 7 crashes for me even before it opens any window.
> 
> Yup, exactly. You can see the underlying error by trying to open it with any of the kiwix-tools from commandline, i.e.

No, I mean the Kiwix desktop for Windows crashes even before I have a chance to open the file -- no GUI pops up at all.

**Comment by JGKle** [comment]
Oh, weird. I'm on Win10 - haven't had any issues with it, though I personally actually use kiwix-serve primarily.  I just mentioned Desktop as I think it's the most common interface for Windows users.  Were you able to reproduce it with kiwix-serve?

**Comment by vss-devel** [comment]
kiwix-serve.exe can't even start at the Windows 7 complaining missing entry point_create_locate at the msvcrt.dll.

**Comment by vss-devel** [comment]
> kiwix-serve.exe prepaid-data-sim-card.wikia.com.zim
> ```
> 
> The error it shows (same as kiwix-manage, & presumably the same underlying error that crashes the desktop app) is:
> 
> ```
> Assertion failed at ../../SOURCE/libzim_release/src/file_reader.cpp:88
>  offset.v[1012801] < _size.v[1012801]
> ```

Perhaps it would be better to ask the libzim developers about this issue.

**Comment by JGKle** [comment]
>>kiwix-serve.exe can't even start at the Windows 7 complaining missing entry point_create_locate at the msvcrt.dll.

Must be some missing dependency on your system, or it doesn't support Windows 7 (which has been deprecated & is no longer receiving updates from MS).  Try in a Win10 VM?

>>Perhaps it would be better to ask the libzim developers about this issue.

I did report it to them ~7 months ago. The view seems to be that this only happens with zims produced by zimmer, not any of the official zims or from any other sources, so it's an issue with zimmer.

**Comment by vss-devel** [comment]
As an example see https://github.com/openzim/libzim/issues/196

But frankly speaking I'm only interested in Linux and Android versions of the Kiwix. I'm sorry, but perhaps it's easier to remove the Windows (and MacOS) from the Redme.

**Comment by JGKle** [comment]
Bummer.  Seems like with all the work you've already put in & how close it is, it'd be nice to have this great tool usable by as wide an audience as possible (aka by producing compatible zims), but if time doesn't permit, I understand. Your software, your call :)

**Comment by vss-devel** [comment]
Well, it's quite possible it's a bug /design flaw in the libzim.

So, the Kiwix desktop at the Linux VM?

**Comment by JGKle** [comment]
>>So, the Kiwix desktop at the Linux VM?

Sorry? What do you mean? I'm using kiwix-serve on Linux, just suggested testing it in a Win10VM, since it seems like it might not work on Win7 anymore...?

**Comment by vss-devel** [comment]
Sorry, it should read that the kiwix-serve doesn't show such an issue on the Linux.

**Comment by JGKle** [comment]
...Oops, sorry, I miswrote too~ I meant to say that I'm using kiwix-serve on Windows, hehe.

But yeah, I see that the zimmer zims only fail on Win, not Linux.

Unfortunately Linux might not be feasible for many users, but I understand if it's not a priority to support all platforms.

**Comment by vss-devel** [comment]
BTW if I remember correctly the Win10 has its own facility to run Linux apps semi/natively.

**Comment by vss-devel** [comment]
Also AFAIK there is a pure JS implementation of the Kiwix.

Something like https://github.com/kiwix/kiwix-js-windows.

**Comment by JGKle** [comment]
Yup, you're thinking of WSL, a cygwin-like Linux environment that more advanced users can install on recent versions of Win10.

**Comment by vss-devel** [comment]
As it's fine for Linux Kiwix, but not for Windows version then the issue needs to be addressed to the Kiwix developers.
