### ISSUE TITLE
Internal links in the zim inacessible

### ISSUE THREAD

**Issue by LAfricain** [vss-devel/zimmer#2]
In my zim file, the internal links and not accessible. Exemple, in the main folder (name data) I have different folders for each authors, exemple:
./data/Augustin/leters/A/
 but when I click on the link in kiwix, I have a blank page. 
But if I do a search I can find the files...

**Comment by vss-devel** [comment]
> internal links and not accessible. 

Actually [ZIM file format](http://www.openzim.org/wiki/ZIM_file_format#URLs) forbids absolute URLs, but this could be a temporary solution:

Try to change line 695 from 
 `link.pathname = '../' + nameSpace + '/' + link.pathname;`
to 
 `link.pathname = '/' + nameSpace + '/' + link.pathname;`

**Comment by LAfricain** [comment]
It's worse,  Now even the page after the welcome page don't display the  link is: zim://A/./_LISTE_DES_AUTEURS.html usually it is: zim://A/_LISTE_DES_AUTEURS.html
Maybe I need to change the link in the welcome page?
With zimwriterfs I haven't this problem.

**Comment by vss-devel** [comment]
> It's worse, Now even the page after the welcome page don't display the link is: zim://A/./_LISTE_DES_AUTEURS.html usually it is: zim://A/_LISTE_DES_AUTEURS.html

What is the path to the welcome page in your source? 
URL in the welcome page in your source?

**Comment by vss-devel** [comment]
I've improved Url conversion function. Check the commit  62844ef.

**Comment by LAfricain** [comment]
YES!!! It seems to do... I tested just with one folder. Now i'm going to do with all.

**Comment by LAfricain** [comment]
It's ok with the new commit it runs...

**Comment by vss-devel** [comment]
> It's ok with the new commit it runs...

Then I'm closing this issue. Thanks for cooperation!
