### ISSUE TITLE
npm install fails (on "sharp"?)

### ISSUE THREAD

**Issue by archenemies** [vss-devel/zimmer#20]
This is the error I get:

    $ npm install
    ...
    > sharp@0.22.1 install /home/user/pkg-tmp/zimmer/node_modules/sharp
    > (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)

    info sharp Detected globally-installed libvips v8.10.2
    info sharp Building from source via node-gyp
    make: Entering directory '/home/user/pkg-tmp/zimmer/node_modules/sharp/build'
      TOUCH Release/obj.target/libvips-cpp.stamp
      CXX(target) Release/obj.target/sharp/src/common.o
      CXX(target) Release/obj.target/sharp/src/metadata.o
      CXX(target) Release/obj.target/sharp/src/stats.o
    ../src/stats.cc: In member function ‘virtual void StatsWorker::HandleOKCallback()’:
    ../src/stats.cc:130:37: error: no matching function for call to ‘v8::Array::Set(int&, v8::Local<v8::Object>&)’
      130 |         channels->Set(i, channelStat);
          |                                     ^
    In file included from /home/user/.cache/node-gyp/15.8.0/include/node/node.h:63,
                     from ../src/stats.cc:19:
    /home/user/.cache/node-gyp/15.8.0/include/node/v8.h:3716:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, v8::Local<v8::Value>, v8::Local<v8::Value>)’
     3716 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context,
          |                                     ^~~
    /home/user/.cache/node-gyp/15.8.0/include/node/v8.h:3716:37: note:   candidate expects 3 arguments, 2 provided
    /home/user/.cache/node-gyp/15.8.0/include/node/v8.h:3719:37: note: candidate: ‘v8::Maybe<bool> v8::Object::Set(v8::Local<v8::Context>, uint32_t, v8::Local<v8::Value>)’
     3719 |   V8_WARN_UNUSED_RESULT Maybe<bool> Set(Local<Context> context, uint32_t index,
          |                                     ^~~
    /home/user/.cache/node-gyp/15.8.0/include/node/v8.h:3719:37: note:   candidate expects 3 arguments, 2 provided
    make: *** [sharp.target.mk:170: Release/obj.target/sharp/src/stats.o] Error 1
    make: Leaving directory '/home/user/pkg-tmp/zimmer/node_modules/sharp/build'
    gyp ERR! build error
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (node:events:378:20)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    gyp ERR! System Linux 5.10.13-arch1-2
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/user/pkg-tmp/zimmer/node_modules/sharp
    gyp ERR! node -v v15.8.0
    gyp ERR! node-gyp -v v7.1.2
    gyp ERR! not ok
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! sharp@0.22.1 install: `(node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)`
    npm ERR! Exit status 1
    npm ERR!
    npm ERR! Failed at the sharp@0.22.1 install script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

    npm ERR! A complete log of this run can be found in:
    npm ERR!     /home/user/.npm/_logs/2021-02-13T20_51_17_707Z-debug.log

**Comment by vss-devel** [comment]
The user managed to make it through.

**Comment by archenemies** [comment]
I still get the same error on `npm install`, it just doesn't seem to prevent Zimmer from working.

**Comment by vss-devel** [comment]
Do you use `node` version >= 10.4.0?

**Comment by archenemies** [comment]
$ node --version
    v15.8.0

**Comment by vss-devel** [comment]
OK, then please try node version 10.x.x or 12.x.x.

**Comment by archenemies** [comment]
I can downgrade "node", if you want to walk me through it and maybe explain the reason, otherwise it sounds like neither of us really have time to investigate this issue. (I'm not too familiar with Node or JavaScript, and just reported the error message out of habit)
