### ISSUE TITLE
can it be restarted?

### ISSUE THREAD

**Issue by archenemies** [vss-devel/zimmer#21]
Thank you for this tool, and I've managed to get it working, but it looks like it's taking a very long time to download Wiktionary, I think it's been running for a few days.

    time ./wikizimmer.js https://en.wiktionary.org/wiki/toll

I couldn't figure out if it's able to restart the download, if I should happen to stop it part-way through.

Also curious if I could get faster results using `wget` (or some [variant with multiple threads](https://stackoverflow.com/q/3430810)) to download the whole site recursively, but I haven't played with that yet. And then use `zimwriterfs`? Will be grateful for any pointers.

**Comment by vss-devel** [comment]
No, the restart feature isn't implemented so far. 

As for the parallel page fetching the Wikipedia and other Mediawiki servers will ban you for concurrent requests, so this feature was removed from wikizimmer.

Yes, after wikizimmer has finished you'd run the zimmer.js to get your zim file. Please check with usage section of the readme.

**Comment by archenemies** [comment]
Thanks for the information

**Comment by archenemies** [comment]
Any idea how long it takes to download Wikipedia?

**Comment by vss-devel** [comment]
No, I have no idea.
