### ISSUE TITLE
isCompressible !mimeType undefined

### ISSUE THREAD

**Issue by SHA85** [vss-devel/zimmer#4]
I have error in running this command ">node zimmer --optimg my.wikipedia.org".

This is error message : "isCompressible !mimeType undefined <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 0e 00 00 00 20 08 06 00 00 00 22 ee 49 97 00 00 01 a2 49 44 41 54 78 01 b5 93 05 6a 6b 51 10 ... > cog-sprite.png".

**Comment by vss-devel** [comment]
Could you please check if "--no-download-errors" helps you?

**Comment by vss-devel** [comment]
I've just downloaded your wiki and it went without the error indicated. Could you please try take the latest commit from here: https://github.com/vss-devel/zimmer/archive/master.zip ?

**Comment by vss-devel** [comment]
I can't reproduce the error. Could you please try the latest commit?

**Comment by SHA85** [comment]
Sorry vss-devel, my error is connection lost when downloading Wikipedia. Thank you!
