### ISSUE TITLE
#ca-history on Fandom Wikis

### ISSUE THREAD

**Issue by JGKle** [vss-devel/zimmer#6]
Attempting to download a wiki from Fandom:

node wikizimmer http://prepaid-data-sim-card.wikia.com/wiki/Alaska

...dies at wikizimmer.js:853:45.  This is because historyLink was undefined.  Up on line 851 it's looking for dom('#ca-history a').attr('href'), whereas on these wikis, the a tag itself is #ca-history.  Fixed by:

dom('#ca-history').attr('href')

Perhaps the code could/should test for both cases, before dying :)

**Comment by JGKle** [comment]
Addendum: although that makes it "not die," it still doesn't find the API URL correctly.   And (just to test) if I simply hardcode the API URL

        wiki.apiUrl = "http://prepaid-data-sim-card.wikia.com/api.php"

...It's then able to find the list of articles, but the html it downloads is blank.  So I guess there's something about this wiki with which zimmer isn't compatible :/

**Comment by vss-devel** [comment]
Please give a try for the commit above.

**Comment by JGKle** [comment]
Perfect, that did it!  Thanks for the super quick turnaround :D
