### ISSUE TITLE
npm install no longer successful

### ISSUE THREAD

**Issue by JGKle** [vss-devel/zimmer#7]
Hi; as of the current version, "npm install" is no longer working (it was the last time I cloned zimmer, last November). 

Here's a screenshot of the cmd where the error is reported: http://take.ms/Cf7bX

Stack trace:
111 verbose stack Error: xz@1.4.0 install: `node-gyp rebuild`
111 verbose stack Exit status 1
111 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
111 verbose stack     at emitTwo (events.js:126:13)
111 verbose stack     at EventEmitter.emit (events.js:214:7)
111 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
111 verbose stack     at emitTwo (events.js:126:13)
111 verbose stack     at ChildProcess.emit (events.js:214:7)
111 verbose stack     at maybeClose (internal/child_process.js:915:16)
111 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
112 verbose pkgid xz@1.4.0
113 verbose cwd C:\Users\Metal450\Desktop\.NoSync\zimmer
114 verbose Windows_NT 10.0.14393
115 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
116 verbose node v8.12.0
117 verbose npm  v6.4.1
118 error code ELIFECYCLE
119 error errno 1
120 error xz@1.4.0 install: `node-gyp rebuild`
120 error Exit status 1
121 error Failed at the xz@1.4.0 install script.
121 error This is probably not a problem with npm. There is likely additional logging output above.
122 verbose exit [ 1, true ]

**Comment by vss-devel** [comment]
Could you please try to replace package.json with this one: [package.json.txt](https://github.com/vss-devel/zimmer/files/2753069/package.json.txt)?

Apparently xz can't be built on Windows (see https://github.com/robey/node-xz/issues/8), but it's not required neither for zimmer.js nor for wikizimmer.js. It's only needed for the test script unzimmer.js which isn't required for normal operation, so zx can be made an optional dependency.

**Comment by JGKle** [comment]
Yup, looks like that did it.  (Though just so you know, it still shows a big red ERROR in the log, which is likely to be confusing - I later realized that it's still erroring out, but then just ignoring that error).

**Comment by vss-devel** [comment]
Perhaps I need to have another thought on this. Meanwhile I've put it into the 421ab5f05fcf0b2dbfa8ddffff7e717d26712ea8. Thanks for checking this out!
