### ISSUE TITLE
ZIM files created with zimmer crash in kiwix software

### ISSUE THREAD

**Issue by urbalazs** [vss-devel/zimmer#8]
The ZIM files, that are created with `zimmer` will be crashed if loading in [Kiwix](https://wiki.kiwix.org/wiki/Main_Page).

How to reproduce the issue:

1. Dump any wiki (e. g. https://wiki.kiwix.org/wiki/Main_Page).

```
./wikizimmer https://wiki.kiwix.org/wiki/Main_Page
```

2. Create a ZIM file with `zimmer`.

```
./zimmer.js --favicon favicon.png --title "Kiwix Wiki" --description "The whole Kiwix wiki." --creator "Kiwix" --publisher "John Doe" wiki.kiwix.org kiwix-zimmer.zim
```

3. Try to load the resulted ZIM file in any Kiwix viewer (I tried to load in the 64 bit GNU/Linux version and in kiwix-serve). All viewer will crash.

4. Create the ZIM file again, but now with [zimwriterfs](https://download.openzim.org/release/zimwriterfs/).

```
./zimwriterfs --welcome=A/Main_Page.html --favicon=favicon.png --language=eng --title="Kiwix Wiki" --description="The whole Kiwix wiki." --creator=Kiwix --publisher="John Doe" ./wiki.kiwix.org kiwix-zimwriterfs.zim
```

5. Try to load the resulted ZIM file in any Kiwix viewer. It works fine.

**Comment by vss-devel** [comment]
This is due to a bug in libzim which kiwix software is using. Please feel free to add your comments to the https://github.com/openzim/libzim/issues/196.

**Comment by vss-devel** [comment]
A workaround is implemented in zimmer.js

**Comment by vss-devel** [comment]
Seems to be fine with Kiwix Linux/Android.
