### ISSUE TITLE
`zimmer.js --welcome` seems not to work with any argument

### ISSUE THREAD

**Issue by naoph** [vss-devel/zimmer#9]
Say for instance a wiki at `example.com` is downloaded with wikizimmer.js, creating a directory also named `example.com`. The desired default/main page is `example.com/A/Main_Page.html`. Regardless of which of the following are specified as the argument for `zimmer.js --welcome`, the main page seems to be selected arbitrarily and is not Main_Page.html:

  - Main_Page.html
  - /Main_Page.html
  - A/Main_Page.html
  - /A/Main_Page.html
  - example.com/A/Main_Page.html
  - /example.com/A/Main_Page.html

Given that the `--help` text for `--welcome` states "The path must be relative to HTML_DIRECTORY", it seems like one of the first 4 should be correct, but none of those 6 options seems to successfully set the default page.

zimmer.js: built from git as of 421ab5f05fcf0b2dbfa8ddffff7e717d26712ea8 (--version specifies 0.1.0)
node: v11.7.0

**Comment by vss-devel** [comment]
Yes, that's correct. "--welcome" has no function at the moment, my apologies. 

But if you're downloading with wikizimmer.js it should pick up the main page from the wiki automatically. Isn't that the case?

**Comment by naoph** [comment]
It doesn't seem to to be the case. I downloaded a couple wikis with wikizimmer.js, then passed them each through zimmer.js, and all of the resulting zim files seem to use arbitrary articles as their main pages. All of them should have Main_page as their main page.

**Comment by vss-devel** [comment]
Could you please check the commit e06f3c770b77011caca08d9bcd9ee342dd7c21db? This should fix the automatic main page issue (the comment there isn't quite correct).

**Comment by naoph** [comment]
Perfect, that seems to have fixed it for me, thanks!
